server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory-service/**
          filters:
            - StripPrefix=1